#!/bin/bash
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
apt install unzip -y
unzip awscliv2.zip
sudo ./aws/install
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.7/2022-10-31/bin/linux/amd64/kubectl
sudo chmod +x kubectl
mv kubectl /usr/local/bin
curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin
echo " alias  ku=kubectl" >> .bashrc
echo " alias 'kd=kubectl get deploy' " >> .bashrc
echo " alias 'kn=kubectl get nodes' " >> .bashrc
echo " alias 'kdp=kubectl describe pod ' " >> .bashrc
echo " alias 'kdn=kubectl describe no'" >> .bashrc
echo " alias 'ks=kubectl get svc'" >> .bashrc
source .bashrc
sudo apt update -y
###################
eksctl create cluster --name=eksdemo1 \
                      --region=us-east-1 \
                      --zones=us-east-1a,us-east-1b \
                      --without-nodegroup     
###########
eksctl utils associate-iam-oidc-provider \
    --region us-east-1 \
    --cluster eksdemo1 \
    --approve
############
eksctl create nodegroup --cluster=eksdemo1 \
                       --region=us-east-1 \
                       --name=eksdemo1-ng-public1 \
                       --node-type=t3.medium \
                       --nodes=2 \
                       --nodes-min=2 \
                       --nodes-max=4 \
                       --node-volume-size=20 \
                       --ssh-access \
                       --ssh-public-key=kubernetes \
                       --managed \
                       --asg-access \
                       --external-dns-access \
                       --full-ecr-access \
                       --appmesh-access \
                       --alb-ingress-access
                       

#############to delete the cluster###############################
# it will delete entire cluster 
# eksctl delete cluster eksdemo1
# If you want to delte nodes groups only 
# eksctl delete nodegroup --cluster=eksdemo1 --name=eksdemo1-ng-public1
