#!/bin/bash

# Update system packages
sudo apt update -y

# Check if AWS CLI is already installed
if ! which aws > /dev/null; then
  # Install AWS CLI
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  sudo apt install unzip -y
  unzip awscliv2.zip
  sudo ./aws/install
else
  echo "AWS CLI is already installed."
fi

# Check if kubectl is already installed
if ! which kubectl > /dev/null; then
  # Install kubectl
  curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  sudo chmod +x kubectl
  sudo mv kubectl /usr/local/bin/
else
  echo "kubectl is already installed."
fi

# Check if eksctl is already installed
if ! which eksctl > /dev/null; then
  # Install eksctl
  sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | sudo tar xz -C /usr/local/bin
else
  echo "eksctl is already installed."
fi

# Add kubectl aliases to .bashrc
echo "alias ku='kubectl'" >> ~/.bashrc
echo "alias kd='kubectl get deploy'" >> ~/.bashrc
echo "alias kn='kubectl get nodes'" >> ~/.bashrc
echo "alias kdp='kubectl describe pod'" >> ~/.bashrc
echo "alias kdn='kubectl describe no'" >> ~/.bashrc
echo "alias ks='kubectl get svc'" >> ~/.bashrc

# Reload .bashrc to activate aliases
source ~/.bashrc
